apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ace-serviceping-2
  namespace: openshift-gitops
spec:
  destination:
    namespace: bo-tmp-ace-2
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: ace/kust/overlays/prod
    repoURL: 'https://github.com/bo-gitops-cp4i/gr-cp4i.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
  ignoreDifferences:
  - group: "appconnect.ibm.com"
    kind: "IntegrationRuntime"
    name: "prod-bo-tmp-ace-1-ir"
    jsonPointers:
    - /spec/configurations

