apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: app-7315-00001-gitops
  namespace: app-7315-00001-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  applicationInstanceLabelKey: argocd.argoproj.io/instance
  server:
    route:
      enabled: true
  rbac:
    defaultPolicy: ''
    policy: |
      g, cluster-admins, role:admin
      g, APP-7315-admin, role:admin
      g, APP-7315-dev, role:readonly
    scopes: '[groups]'
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
    provider: dex
