apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns-gitops-for-cp4i.yaml
- cr-argocd-gitops-for-cp4i.yaml
- cr-appproject-cp4i-project.yaml
# labels:
# - includeSelectors: true
#   pairs:
#     app: demo
