apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns-gitops-for-cp4i.yaml
- cr-argocd-gitops-for-cp4i.yaml
- cr-appproject-cp4i-ace-project.yaml
- cr-appproject-cp4i-mq-project.yaml
- groups.yaml
labels:
- includeSelectors: true
  pairs:
    dsv-app-id: app-7315
    variant: production