apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cr-navigator.yaml
- cs-appconnect.yaml
- cs-aut-foundation.yaml
- cs-found-services.yaml
- cs-mq.yaml
- cs-navigator.yaml
- ns-cert-manager.yaml
- ns-cert-manager-operator.yaml
- ns-cp4i.yaml
- ns-ibm-common-svc.yaml
- ns-ibm-licensing.yaml
- og-certmgr.yaml
- og-ibm-licensing.yaml
- sub-certmgr.yaml
- sub-found-services.yaml
- sub-ibm-licensing.yaml
- sub-navigator.yaml