apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  creationTimestamp: null
  name: ace-boutilfyre-barauth-cs
  namespace: bo-tmp-ace-1
data:
  configuration: eyJhdXRoVHlwZSI6IkJBU0lDX0FVVEgiLCJjcmVkZW50aWFscyI6eyJ1c2VybmFtZSI6IiIsInBhc3N3b3JkIjoiIiwiaW5zZWN1cmVTc2wiOiJ0cnVlIn19

