apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  creationTimestamp: null
  name: bo-artifactory-ace
data:
  configuration: eyJhdXRoVHlwZSI6IkJBU0lDX0FVVEgiLCJjcmVkZW50aWFscyI6eyJ1c2VybmFtZSI6InJlYWRlci1wcm9qZWN0LWVwaXNvY3AiLCJwYXNzd29yZCI6IjdnanEzbjhtfm5XQGdha2ZUKzZXIiwiaW5zZWN1cmVTc2wiOiJ0cnVlIn19

